In [2]:
#inheritance

        self.__privatclass Parent(object):
    def _protected(self):
        pass

    def __private(self):
        pass

class Child(Parent):
    def foo(self):
        self._protected()   

    def bar(self):e()


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [4]:
class Parent(object):
    def _protected(self):
        pass

    def __private(self):
        print("Is it really private?")

class Child(Parent):
    def foo(self):
        self._protected()

    def bar(self):
        self.__private()

c = Child(
c._Parent__private()

Is it really private?


In [8]:
# 1. REGULAR EXPRESSION
# 

# #findall() function
#  
# import re
# text = "Python assignment"
# x = re.findall("n",text)
# print(x)


In [7]:
#search() function

import re
text = "Python assignment"
x = re.search("Python", text)
x


<re.Match object; span=(0, 6), match='Python'>

In [10]:
#split() function

import re
text = "Python"
x = re.split("\s",text)
x


['Python']

In [9]:
#sub() function

import re
text = "programming"
x = re.sub("p","P",text)
x


'Programming'

In [85]:
2. #AGGREGATE FUNCTIONS
# **i) ONE DIMENSIONAL ARRAY**import numpy as np
x = np.random.randint(1,2,3)
x


array([1, 1, 1])

In [87]:
import numpy as np
x = np.random.randint(1,11,4)
x

array([5, 7, 2, 6])

In [88]:
#sum() function

x=np.sum(x)
x

20

In [89]:
#min() function

x=np.min(x)
x

20

In [90]:
#prod() function
a=np.prod(a)
x


20

In [91]:
#mean
x=np.mean(x)
x


20.0

In [40]:
#standard deviation
x=np.std(x)
x


0.0

In [92]:
#variance
x=np.var(x)
x

0.0

In [93]:
#index of minimum value
x=np.argmin(x)
x

0

In [28]:
#index of maximum value
x=np.argmax(a)
x

0

In [29]:
x=np.median(a)
x


20.0

In [31]:
x=np.any(a)
x

True

In [32]:
x=np.all(a)
x

True

In [34]:
#multidimensionalaray
A =np.random.randint(10,12,(2,1))
A

array([[11],
       [10]])

In [35]:
#sum() function
x=A.sum()
y=A.sum(axis=0)
z=A.sum(axis=1)
print(x)
print(y)
print(z)


21
[21]
[11 10]


In [36]:
#product function

x=np.prod(A)
y=np.prod(A,axis=0)
z=np.prod(A,axis=1)
print(x)
print(y)
print(z)


110
[110]
[11 10]


In [44]:
#mean

x=np.mean(A)
x


10.5

In [45]:
#standard deviation

x=np.std(A)
x


0.5

In [46]:
#variance
np.var(A)


0.25

In [47]:
#minimum
x=np.min(A)
x

10

In [48]:
#maximum

np.max(A)

11

In [49]:
#index of minimum value
np.argmin(A)

1

In [50]:
#index of maximum value
np.argmax(A)


0

In [96]:
#median
np.median(A)

10.5

In [52]:
#percentile
np.percentile(A,3)

10.03

In [97]:
np.any(A)


True

In [98]:
np.all(A)

True

In [94]:
#exceptionalhandling
x = "hi"
print x

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(x)? (2736285378.py, line 3)

In [95]:
x = 5/0
print(x)

ZeroDivisionError: division by zero

In [58]:
arr_1 = [10,20,30,40,50]
print(arr_1[5])

IndexError: list index out of range

NameError: name 'greater' is not defined

In [60]:
import numpy as np
import pandas as pd
s = np.array([1,2,3,4,5])



In [61]:
#equal
s == 3


array([False, False,  True, False, False])

In [62]:
#not equal
s != 4

array([ True,  True,  True, False,  True])

In [63]:
#greater than or equal to
s >= 5


array([False, False, False, False,  True])

In [64]:
#less than or equal to
s <= 1


array([ True, False, False, False, False])

In [65]:
#greater than
s > 0


array([ True,  True,  True,  True,  True])

In [66]:
#less than
s < 0


array([False, False, False, False, False])

In [67]:
#compound expressions
(5 * s) == (s ** 5)


array([False, False, False, False, False])

In [68]:
x = np.random.randint(1,10,(3,4))
x


array([[4, 1, 8, 2],
       [7, 9, 9, 3],
       [4, 1, 8, 5]])

In [69]:
np.sum(x < 3)

3

In [70]:
np.sum(x < 6, axis=1)

array([3, 1, 3])

In [71]:
np.any(x < 0)

False

In [72]:
np.all(x < 10)

True

In [73]:
np.all(x == 6)

False

In [74]:
np.all(x < 8, axis=1)

array([False, False, False])

In [75]:
#booleanoperators
bool(0),bool(10)

(False, True)

In [76]:
bool(0 and 10)

False

In [77]:
bool(0 or 100)

True

In [78]:
x = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
y = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
x & y

array([ True, False,  True, False,  True, False])

In [100]:
x = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
y = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
x | y


array([ True,  True,  True, False,  True,  True])

In [99]:
x = np.arange(5)
(x > 4) & (x < 2)

array([False, False, False, False, False])

In [81]:
class parent:
    def __init__(self,name,age):
        self.pname = name
        self.page = age
    
    def displayAge(self):
        print("Age:",self.page)
        
ob = parent("Father",40)
print("Parent:",ob.pname)
ob.displayAge()


Parent: Father
Age: 40


In [82]:
#single inheritance

class Parent():
       def first(self):
           print('this is a parent class')
class Child(Parent):
       def second(self):
          print('this is a child class')
 
object = Child()
object.first()
object.second()



this is a parent class
this is a child class


In [83]:
#multilevel inheritance

class Parent:
      def myfunc1(self):
          print("this is Parent class")
class Child(Parent):
      def myfunc2(self):
          print("this is Child class")
class Child2(Child):
      def myfunc3(self):
        print("this is Another child class")
object = Child2()
object.myfunc1()
object.myfunc2()
object.myfunc3()


this is Parent class
this is Child class
this is Another child class


In [84]:
#multiple inheritance

class Parent:
   def func1(self):
        print("parent class")
class Parent2:
   def func2(self):
        print("another parent class")
class Child(Parent , Parent2):
    def func3(self):
        print("child class")
 
object = Child()
object.func1()
object.func2()
object.func3()


parent class
another parent class
child class
